/*
 * UI contract: テストが依存してよい安定名（data-ui 属性値）。
 *
 * - これらの名前は日本語文言の変更で壊れない契約。Playwright/Testing Library から参照する。
 * - DOM 構造や CSS class には依存させない。
 * - 詳細とポリシーは docs/dev/ui-contract.md。
 */
export const UI = {
  // 期間（データ抽出条件）。ヘッダー中央の「現在コンテキスト表示」。ホーム/財務諸表/仕訳で共有
  period: {
    // ヘッダーの日付チップ（透明な date input を重ねた 1 タップ選択）
    dateTrigger: 'period.date.trigger',
    dateInput: 'period.date.input',
    // 年・全期間はロジックを維持するが、現在は UI から到達させない。
    yearPicker: 'period.year.picker',
    yearRow: 'period.year.row',
    allRow: 'period.all.row',
    // トレンド（SVG グラフ）
    trend: 'period.trend',
    trendChart: 'period.trend.chart',
    trendPoint: 'period.trend.point',
  },
  dashboard: {
    view: 'dashboard.view',
    // 日常入力 3 種（ホーム下部の固定バー＝主導線）
    entryBar: 'dashboard.entryBar',
    income: 'dashboard.entry.income',
    expense: 'dashboard.entry.expense',
    transfer: 'dashboard.entry.transfer',
    // 収支/財政状態の項目別ボタン（タップで各項目の「内訳 + 推移」ページへ）。
    statRevenue: 'dashboard.stat.revenue',
    statExpense: 'dashboard.stat.expense',
    statNetIncome: 'dashboard.stat.netIncome',
    statAssets: 'dashboard.stat.assets',
    statLiabilities: 'dashboard.stat.liabilities',
    statNetAssets: 'dashboard.stat.netAssets',
    // 当月の仕訳プレビュー
    journalPreview: 'dashboard.journal.preview',
    journalOpenAll: 'dashboard.journal.openAll',
  },
  // 収入の内訳
  incomeBreakdown: {
    view: 'incomeBreakdown.view',
    row: 'incomeBreakdown.row',
    total: 'incomeBreakdown.total',
  },
  // 支出の内訳
  expenseBreakdown: {
    view: 'expenseBreakdown.view',
    categoryList: 'expenseBreakdown.categoryList',
    categoryRow: 'expenseBreakdown.categoryRow',
    normalExpense: 'expenseBreakdown.normalExpense',
    monthlyCost: 'expenseBreakdown.monthlyCost',
    total: 'expenseBreakdown.total',
  },
  // 収支
  netIncome: {
    view: 'netIncome.view',
    revenue: 'netIncome.revenue',
    expense: 'netIncome.expense',
    result: 'netIncome.result',
  },
  // 資産の内訳（4 枠: 自由に動かせるお金 / 自由に動かせないお金 / 投資 / 継続コスト台帳）
  assetsBreakdown: {
    view: 'assetsBreakdown.view',
    row: 'assetsBreakdown.row',
    total: 'assetsBreakdown.total',
    freeSubtotal: 'assetsBreakdown.subtotal.free',
    fixedSubtotal: 'assetsBreakdown.subtotal.fixed',
    investmentSubtotal: 'assetsBreakdown.subtotal.investment',
    ledgerSubtotal: 'assetsBreakdown.subtotal.ledger',
    frame: 'assetsBreakdown.frame',
    // 継続コスト台帳の 1 行（残存価値合計・タップで「毎月のもの」へ）
    ledgerRow: 'assetsBreakdown.ledgerRow',
  },
  // 負債の内訳
  liabilitiesBreakdown: {
    view: 'liabilitiesBreakdown.view',
    row: 'liabilitiesBreakdown.row',
    total: 'liabilitiesBreakdown.total',
    shortTermSubtotal: 'liabilitiesBreakdown.subtotal.shortTermDebt',
    longTermSubtotal: 'liabilitiesBreakdown.subtotal.longTermDebt',
    frame: 'liabilitiesBreakdown.frame',
    cashflowLink: 'liabilitiesBreakdown.cashflowLink',
  },
  // 純資産
  netAssets: {
    view: 'netAssets.view',
    row: 'netAssets.row',
    total: 'netAssets.total',
  },
  // 年間・全体（年別の月次表 / 全期間の年次表）
  yearlyOverview: {
    view: 'yearlyOverview.view',
    modeYear: 'yearlyOverview.mode.year',
    modeAll: 'yearlyOverview.mode.all',
    prevYear: 'yearlyOverview.year.previous',
    nextYear: 'yearlyOverview.year.next',
    matrix: 'yearlyOverview.matrix',
  },
  journal: {
    view: 'journal.view',
    list: 'journal.entry.list',
    search: 'journal.search',
    clearAccountFilter: 'journal.filter.clearAccount',
    clearNormalExpenseFilter: 'journal.filter.clearNormalExpense',
    showFuture: 'journal.filter.showFuture',
    filterTag: 'journal.filter.tag',
    entry: {
      save: 'journal.entry.save',
      cancel: 'journal.entry.cancel',
      delete: 'journal.entry.delete',
      reverse: 'journal.entry.reverse',
      detailToggle: 'journal.entry.detailToggle',
      manualSwitch: 'journal.entry.manualSwitch',
      tags: 'journal.entry.tags',
      debitTags: 'journal.entry.debitTags',
      creditTags: 'journal.entry.creditTags',
      monthlyizeRepayToggle: 'journal.entry.monthlyizeRepayToggle',
      monthlyizeRepayAccount: 'journal.entry.monthlyizeRepayAccount',
      monthlyizeRepayCount: 'journal.entry.monthlyizeRepayCount',
      monthlyizeRepayStart: 'journal.entry.monthlyizeRepayStart',
      ccToggle: 'journal.entry.ccToggle',
      ccName: 'journal.entry.ccName',
      ccCategory: 'journal.entry.ccCategory',
      ccEndDate: 'journal.entry.ccEndDate',
      loanArrange: 'journal.entry.loanArrange',
      liabilityCreate: 'journal.entry.liabilityCreate',
      liabilityCreateName: 'journal.entry.liabilityCreate.name',
      liabilityCreateRole: 'journal.entry.liabilityCreate.role',
      liabilityCreateSave: 'journal.entry.liabilityCreate.save',
      date: 'journal.entry.date',
      description: 'journal.entry.description',
      item: 'journal.entry.item',
      flow: 'journal.entry.flow',
      flowSource: 'journal.entry.flow.source',
      flowDestination: 'journal.entry.flow.destination',
      flowError: 'journal.entry.flow.error',
      debitAccount: 'journal.entry.debitAccount',
      creditAccount: 'journal.entry.creditAccount',
      amount: 'journal.entry.amount',
      memo: 'journal.entry.memo',
    },
  },
  accounts: {
    view: 'accounts.view',
    create: 'accounts.create',
    save: 'accounts.save',
    list: 'accounts.list',
    box: 'accounts.box',
    notMovableBadge: 'accounts.notMovableBadge',
    adjust: 'accounts.adjust',
    // アーカイブ/解除ボタン。残高が残る資産・負債は振替シート（EntrySheet transfer 再利用）を経由する
    archiveToggle: 'accounts.archiveToggle',
    openingAmount: 'accounts.openingAmount',
    openingDate: 'accounts.openingDate',
    startDate: 'accounts.startDate',
    endDate: 'accounts.endDate',
    archiveRenameConfirm: 'accounts.archiveRenameConfirm',
    // 「自由に動かせる」チェック（現預金の内訳のみ・OFF = 資金繰りの原資に数えない）
    movable: 'accounts.movable',
    // 返済設定（負債の編集シートのみ）
    repaymentAccount: 'accounts.repaymentAccount',
    repaymentDay: 'accounts.repaymentDay',
    // 並び替えモード（箱内・上下ボタン式）
    reorderToggle: 'accounts.reorder.toggle',
    moveUp: 'accounts.reorder.up',
    moveDown: 'accounts.reorder.down',
  },
  allocations: {
    view: 'allocations.view',
    list: 'allocations.list',
    // 継続コスト資産の 1 項目カード（data-ending="true" = 終了まで1ヶ月以内）
    item: 'allocations.item',
    // 終了した定期ルールと継続コスト資産を再表示する共通トグル
    showCompleted: 'allocations.showCompleted',
    // 統一追加フロー（2択: .rule = くり返し記帳 / .asset = 継続コスト資産の持ち込み）
    unifiedAdd: 'allocations.add',
    addChooser: 'allocations.add.chooser',
    // 定期ルール（くり返し記帳。費用行きは自動で継続コスト化）
    recurringList: 'allocations.recurring.list',
    recurringAdd: 'allocations.recurring.add',
    recurringSheet: 'allocations.recurring.sheet',
    recurringName: 'allocations.recurring.name',
    recurringAmount: 'allocations.recurring.amount',
    recurringEvery: 'allocations.recurring.every',
    recurringFirstPostingDate: 'allocations.recurring.firstPostingDate',
    recurringStartDate: 'allocations.recurring.startDate',
    recurringEndDate: 'allocations.recurring.endDate',
    recurringFrom: 'allocations.recurring.from',
    recurringTo: 'allocations.recurring.to',
    recurringSave: 'allocations.recurring.save',
    recurringAmountChangeDialog: 'allocations.recurring.amountChange.dialog',
    recurringAmountChangeAll: 'allocations.recurring.amountChange.all',
    recurringAmountChangeFromToday: 'allocations.recurring.amountChange.fromToday',
    recurringAmountChangeCancel: 'allocations.recurring.amountChange.cancel',
    recurringEdit: 'allocations.recurring.edit',
    // 終了 = today を排他的終点へ。同じ設定で新しく始める = 系譜なしの独立ルール作成。
    recurringEnd: 'allocations.recurring.end',
    recurringRestart: 'allocations.recurring.restart',
    recurringDelete: 'allocations.recurring.delete',
    // 継続コスト資産シート（登録＝編集の 1 コンポーネント）
    edit: 'allocations.edit',
    editDialog: 'allocations.editDialog',
    editName: 'allocations.edit.name',
    editAmount: 'allocations.edit.amount',
    editStartDate: 'allocations.edit.startDate',
    editEndDate: 'allocations.edit.endDate',
    editQuickSpan: 'allocations.edit.quickSpan',
    editOpenPurchase: 'allocations.edit.openPurchase',
    editExpense: 'allocations.edit.expense',
    editSave: 'allocations.edit.save',
    editImpactWarning: 'allocations.edit.impactWarning',
    // アーカイブ = 終了日の設定（+ 残存価値の回収の振替）
    archive: 'allocations.archive',
    archiveDialog: 'allocations.archiveDialog',
    archiveDate: 'allocations.archive.date',
    archiveTransfer: 'allocations.archive.transfer',
    archiveConfirm: 'allocations.archive.confirm',
  },
  tags: {
    view: 'tags.view',
    create: 'tags.create',
    save: 'tags.save',
    name: 'tags.name',
    list: 'tags.list',
    period: 'tags.period',
    entrySummary: 'tags.summary.entry',
    lineSummary: 'tags.summary.line',
  },
  // 残高補正・初期残高のシート（勘定科目の内訳行・仕訳一覧から開く）。
  adjustments: {
    account: 'adjust.account',
    date: 'adjust.date',
    actual: 'adjust.actual',
    save: 'adjust.save',
    createDialog: 'adjustments.createDialog',
    // 履歴の無い科目の「補正」導線は初期残高登録へ自動分岐する
    openingRegisterDialog: 'adjustments.openingRegister.dialog',
    openingRegisterAmount: 'adjustments.openingRegister.amount',
    openingRegisterDate: 'adjustments.openingRegister.date',
    openingRegisterSave: 'adjustments.openingRegister.save',
    rowEdit: 'adjustments.row.edit',
    rowDelete: 'adjustments.row.delete',
    editDialog: 'adjustments.editDialog',
    editAccount: 'adjustments.edit.account',
    editDate: 'adjustments.edit.date',
    editActual: 'adjustments.edit.actual',
    editSave: 'adjustments.edit.save',
    deleteConfirm: 'adjustments.deleteConfirm',
    openingRowEdit: 'opening.row.edit',
    openingRowDelete: 'opening.row.delete',
    openingEditDialog: 'opening.editDialog',
    openingEditAmount: 'opening.edit.amount',
    openingEditDate: 'opening.edit.date',
    openingEditSave: 'opening.edit.save',
    openingDeleteConfirm: 'opening.deleteConfirm',
  },
  cashflow: {
    view: 'cashflow.view',
    until: 'cashflow.until',
    addSchedule: 'cashflow.schedule.create',
    list: 'cashflow.schedule.list',
    scheduleSave: 'cashflow.schedule.save',
    schedulePost: 'cashflow.schedule.post',
    scheduleName: 'cashflow.schedule.name',
    scheduleAmount: 'cashflow.schedule.amount',
    scheduleAccount: 'cashflow.schedule.account',
    scheduleCounter: 'cashflow.schedule.counter',
    scheduleFlowSource: 'cashflow.schedule.flow.source',
    scheduleFlowDestination: 'cashflow.schedule.flow.destination',
    scheduleInstallments: 'cashflow.schedule.installments',
    liabilityList: 'cashflow.liability.list',
    // カード・ローンの返済予定づくり（負債行から開く）
    repayAdd: 'cashflow.repay.add',
    liabilityRow: 'cashflow.liability.row',
    repaySheet: 'cashflow.repay.sheet',
    repayAmount: 'cashflow.repay.amount',
    repayDate: 'cashflow.repay.date',
    repayFrom: 'cashflow.repay.from',
    repayCount: 'cashflow.repay.count',
    repayPerMonth: 'cashflow.repay.perMonth',
    repaySave: 'cashflow.repay.save',
    freeTrend: 'cashflow.freeTrend',
    futureList: 'cashflow.future.list',
    scheduleEntryTags: 'cashflow.schedule.entryTags',
    scheduleAccountTags: 'cashflow.schedule.accountTags',
    scheduleCounterTags: 'cashflow.schedule.counterTags',
    summary: 'cashflow.summary',
    // 負債行の展開 = 登録済みの返済（未来日付の保存仕訳）。タップで仕訳の編集シートへ
    repaymentsToggle: 'cashflow.repayments.toggle',
    repaymentsList: 'cashflow.repayments.list',
    repaymentRow: 'cashflow.repayments.row',
  },
  settings: {
    view: 'settings.view',
    manageList: 'settings.manage.list',
    exportJson: 'settings.exportJson',
    importJson: 'settings.importJson',
    importFile: 'settings.importFile',
    resetAll: 'settings.resetAll',
    onboardingOpen: 'settings.onboardingOpen',
  },
  nav: {
    home: 'nav.home',
    menuButton: 'nav.menu.button',
    menu: 'nav.menu',
  },
  dialog: {
    confirm: 'dialog.confirm',
    cancel: 'dialog.cancel',
  },
  // 端末/ブラウザ Back の終了確認（appHistory が管理・オーバーレイ登録簿には載せない）
  app: {
    exitConfirm: 'app.exitConfirm',
    // 台帳が読めない / 描画時例外のときの復旧画面（設定へ入って JSON 読み込み・復元）。
    recovery: 'app.recovery',
    recoverySettings: 'app.recovery.settings',
    // VersionError 詰み対策の最終手段（deleteDatabase → reload）
    recoveryWipe: 'app.recovery.wipe',
  },
  // 初期残高の一括登録シート（初回起動時に自動表示・設定から再表示可能）
  onboarding: {
    view: 'onboarding.view',
    amount: 'onboarding.amount',
    registered: 'onboarding.registered',
    save: 'onboarding.save',
    skip: 'onboarding.skip',
  },
  toast: 'toast',
} as const;
