/*
 * UI contract: テストが依存してよい安定名（data-ui 属性値）。
 *
 * - これらの名前は日本語文言の変更で壊れない契約。Playwright/Testing Library から参照する。
 * - DOM 構造や CSS class には依存させない。
 * - 詳細とポリシーは docs/dev/ui-contract.md。
 */
export const UI = {
  dashboard: {
    view: 'dashboard.view',
    // 日常入力 3 種（ホーム上部の主導線）
    income: 'dashboard.entry.income',
    expense: 'dashboard.entry.expense',
    transfer: 'dashboard.entry.transfer',
    // 損益/資産負債サマリー（タップで財務諸表へ）
    openPl: 'dashboard.openPl',
    openBs: 'dashboard.openBs',
  },
  journal: {
    view: 'journal.view',
    list: 'journal.entry.list',
    monthlyRecognition: 'journal.monthlyRecognition',
    search: 'journal.search',
    clearAccountFilter: 'journal.filter.clearAccount',
    showFuture: 'journal.filter.showFuture',
    filterTag: 'journal.filter.tag',
    entry: {
      save: 'journal.entry.save',
      cancel: 'journal.entry.cancel',
      delete: 'journal.entry.delete',
      reverse: 'journal.entry.reverse',
      detailToggle: 'journal.entry.detailToggle',
      manualSwitch: 'journal.entry.manualSwitch',
      tags: 'journal.entry.tags',
      debitTags: 'journal.entry.debitTags',
      creditTags: 'journal.entry.creditTags',
      allocateToggle: 'journal.entry.allocateToggle',
      allocateMonths: 'journal.entry.allocateMonths',
      monthlyizeContinue: 'journal.entry.monthlyizeContinue',
      monthlyizeRepayToggle: 'journal.entry.monthlyizeRepayToggle',
      monthlyizeRepayAccount: 'journal.entry.monthlyizeRepayAccount',
      monthlyizeRepayCount: 'journal.entry.monthlyizeRepayCount',
      monthlyizeRepayStart: 'journal.entry.monthlyizeRepayStart',
      date: 'journal.entry.date',
      description: 'journal.entry.description',
      debitAccount: 'journal.entry.debitAccount',
      creditAccount: 'journal.entry.creditAccount',
      amount: 'journal.entry.amount',
      memo: 'journal.entry.memo',
    },
  },
  statements: {
    view: 'statements.view',
    profitAndLoss: 'statements.profitAndLoss',
    balanceSheet: 'statements.balanceSheet',
    tabPl: 'statements.tab.pl',
    tabBs: 'statements.tab.bs',
    asOf: 'statements.asOf',
    // 科目行（クリックで Journal へドリルダウン）
    row: 'statements.row',
  },
  accounts: {
    view: 'accounts.view',
    create: 'accounts.create',
    save: 'accounts.save',
    list: 'accounts.list',
    type: 'accounts.type',
    role: 'accounts.role',
  },
  allocations: {
    view: 'allocations.view',
    list: 'allocations.list',
    showCompleted: 'allocations.showCompleted',
  },
  tags: {
    view: 'tags.view',
    create: 'tags.create',
    save: 'tags.save',
    name: 'tags.name',
    list: 'tags.list',
    period: 'tags.period',
    entrySummary: 'tags.summary.entry',
    lineSummary: 'tags.summary.line',
  },
  adjustments: {
    view: 'adjustments.view',
    account: 'adjust.account',
    date: 'adjust.date',
    kind: 'adjust.kind',
    actual: 'adjust.actual',
    save: 'adjust.save',
  },
  cashflow: {
    view: 'cashflow.view',
    addSchedule: 'cashflow.schedule.create',
    list: 'cashflow.schedule.list',
    scheduleSave: 'cashflow.schedule.save',
    schedulePost: 'cashflow.schedule.post',
    scheduleName: 'cashflow.schedule.name',
    scheduleAmount: 'cashflow.schedule.amount',
    scheduleAccount: 'cashflow.schedule.account',
    scheduleCounter: 'cashflow.schedule.counter',
    scheduleInstallments: 'cashflow.schedule.installments',
    // 予定CF のタグ欄（実績化時に仕訳へコピーされる）
    scheduleEntryTags: 'cashflow.schedule.entryTags',
    scheduleAccountTags: 'cashflow.schedule.accountTags',
    scheduleCounterTags: 'cashflow.schedule.counterTags',
    summary: 'cashflow.summary',
    addReserve: 'cashflow.reserve.create',
    reserveList: 'cashflow.reserve.list',
    reserveSave: 'cashflow.reserve.save',
    reserveName: 'cashflow.reserve.name',
    // 資金目標
    addGoal: 'cashflow.goal.create',
    goalList: 'cashflow.goal.list',
    goalSave: 'cashflow.goal.save',
    goalName: 'cashflow.goal.name',
    goalAmount: 'cashflow.goal.amount',
    goalDate: 'cashflow.goal.date',
  },
  settings: {
    view: 'settings.view',
    // 管理セクション（補助画面への遷移リスト）。各行は settings.manage.<screen>
    manageList: 'settings.manage.list',
    exportJson: 'settings.exportJson',
    importJson: 'settings.importJson',
    importFile: 'settings.importFile',
    resetAll: 'settings.resetAll',
    expectedReturn: 'settings.expectedReturn',
  },
  nav: {
    home: 'nav.home',
    menuButton: 'nav.menu.button',
    menu: 'nav.menu',
  },
  dialog: {
    confirm: 'dialog.confirm',
    cancel: 'dialog.cancel',
  },
  toast: 'toast',
} as const;
